<template>
  <view class="page">
    <view class="profile"><view class="avatar">{{ (user.username || 'U').slice(0,1).toUpperCase() }}</view><view><text class="name">{{ user.username }}</text><text class="email">{{ user.email }}</text></view><text class="level">{{ entitlement.plan }}</text></view>
    <view class="asset-card"><text class="eyebrow">MY BENEFITS</text><text class="asset-title">我的权益</text><view class="assets"><view><text>{{ user.free_quota || 0 }}</text><text>免费次数</text></view><view><text>{{ entitlement.paid_quota }}</text><text>购买次数</text></view><view><text>{{ entitlement.report_quota }}</text><text>报告权益</text></view><view><text>{{ entitlement.visual_quota }}</text><text>视觉权益</text></view></view><button @click="goPlans">升级权益</button></view>
    <view class="menus"><view @click="goPlans"><text class="icon">惠</text><view><text>套餐与订单</text><text>查看套餐及模拟支付记录</text></view><text>›</text></view><view @click="goReports"><text class="icon green">报</text><view><text>高级报告</text><text>管理候选名字分析报告</text></view><text>›</text></view><view @click="goVisual"><text class="icon brown">图</text><view><text>品牌视觉</text><text>创建 Logo 与品牌板概念</text></view><text>›</text></view><view @click="goKnowledge"><text class="icon gray">库</text><view><text>企业知识库</text><text>管理品牌参考资料</text></view><text>›</text></view></view>
    <view class="mock-note">第三阶段服务已连接后端；支付入口使用支付宝沙箱，不会产生真实扣款。</view>
    <button class="logout" @click="logout">退出登录</button>
  </view>
</template>
<script setup>
import { ref } from 'vue'; import { onShow } from '@dcloudio/uni-app'; import http from '@/http/http.js';
const user=ref({}); const entitlement=ref({plan:'免费版',paid_quota:0,report_quota:0,visual_quota:0});
const mapType=v=>({name_generate:'paid_quota',report_generate:'report_quota',visual_generate:'visual_quota'}[v]);
onShow(async()=>{ if(!uni.getStorageSync('token')) return uni.reLaunch({url:'/pages/login/login'}); user.value=uni.getStorageSync('user')||{}; try{const accounts=await http.getEntitlementAccounts();const next={plan:accounts.length?'已购权益':'免费版',paid_quota:0,report_quota:0,visual_quota:0};accounts.forEach(a=>{const key=mapType(a.entitlement_type);if(key)next[key]+=Number(a.balance||0);});entitlement.value=next;}catch(e){console.error(e);} });
const goPlans=()=>uni.navigateTo({url:'/pages/plans/plans'}); const goReports=()=>uni.navigateTo({url:'/pages/reports/reports'}); const goVisual=()=>uni.navigateTo({url:'/pages/visual/visual'}); const goKnowledge=()=>uni.navigateTo({url:'/pages/knowledge/knowledge'});
const logout=()=>uni.showModal({title:'退出登录',content:'确定退出当前账号？',success:({confirm})=>{if(!confirm)return;uni.removeStorageSync('token');uni.removeStorageSync('user');uni.reLaunch({url:'/pages/login/login'});}});
</script>
<style scoped>
.page{min-height:100vh;padding:32rpx 30rpx 90rpx;box-sizing:border-box;color:#292620;background:#f7f4ee}.profile{display:flex;align-items:center;gap:18rpx;padding:28rpx;border-radius:22rpx;background:#fff}.avatar{display:flex;align-items:center;justify-content:center;width:82rpx;height:82rpx;color:#fff;border-radius:50%;background:#4b6759;font-size:30rpx;font-weight:700}.profile>view:nth-child(2){flex:1}.name,.email{display:block}.name{font-size:29rpx;font-weight:700}.email{margin-top:5rpx;color:#938a7e;font-size:20rpx}.level{padding:7rpx 13rpx;color:#8a6328;border-radius:20rpx;background:#f7eacb;font-size:18rpx}.asset-card{margin-top:22rpx;padding:30rpx;color:#fff;border-radius:25rpx;background:linear-gradient(135deg,#2f493d,#5f786a)}.eyebrow,.asset-title{display:block}.eyebrow{color:#d6e1db;font-size:16rpx;letter-spacing:3rpx}.asset-title{margin-top:7rpx;font-size:33rpx;font-weight:700}.assets{display:grid;grid-template-columns:1fr 1fr;gap:14rpx;margin-top:22rpx}.assets view{padding:16rpx;border-radius:13rpx;background:rgba(255,255,255,.1)}.assets text{display:block}.assets text:first-child{font-size:34rpx;font-weight:700}.assets text:last-child{color:rgba(255,255,255,.65);font-size:18rpx}.asset-card button{margin:22rpx 0 0;color:#365145;background:#fff}.menus{margin-top:24rpx;overflow:hidden;border-radius:22rpx;background:#fff}.menus>view{display:flex;align-items:center;gap:18rpx;padding:24rpx;border-bottom:1rpx solid #eee9e1}.menus>view>view{flex:1}.menus text{display:block}.menus view view text:first-child{font-size:25rpx;font-weight:700}.menus view view text:last-child{margin-top:5rpx;color:#9b9286;font-size:19rpx}.icon{display:flex!important;align-items:center;justify-content:center;width:58rpx;height:58rpx;color:#fff;border-radius:15rpx;background:#b07b4f}.icon.green{background:#547161}.icon.brown{background:#826b5d}.icon.gray{background:#777d78}.mock-note{margin-top:22rpx;padding:20rpx;color:#8c7960;border-radius:15rpx;background:#fff7e8;font-size:19rpx;line-height:1.6}.logout{margin-top:25rpx;color:#a45149;background:#fff}
</style>
